<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.pagelibrary.com.parkway.Repository" tests="2" time="0.004" ignored="0" failures="0" timestamp="06 Aug 2018 05:33:03 GMT" skipped="1" hostname="IBM088-PC0BQ4M1" errors="1">
  <testcase name="setextent" time="0.000" classname="com.pagelibrary.com.parkway.Repository">
    <error type="java.lang.Error" message="Unresolved compilation problems: 
	The constructor ExtentReports(String) is undefined
	The method attachReporter(ExtentReporter...) in the type ExtentReports is not applicable for the arguments (ExtentReports)
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
	The constructor ExtentReports(String) is undefined
	The method attachReporter(ExtentReporter...) in the type ExtentReports is not applicable for the arguments (ExtentReports)

	at com.pagelibrary.com.parkway.Repository.setextent(Repository.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setextent -->
  <testcase name="enterinvalid_invalid" time="0.004" classname="com.pagelibrary.com.parkway.Repository">
    <skipped/>
  </testcase> <!-- enterinvalid_invalid -->
</testsuite> <!-- com.pagelibrary.com.parkway.Repository -->
